server:
  port: 8270

spring:
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    userName: root
    password: 1111
    url: jdbc:mysql://localhost:3302/triple_db


logging:
  level:
    org:
      hibernate:
        sql: DEBUG
        type: trace


# docker run -it -d -p 3302:3306 --name triple-travelers-club --platform=linux/amd64 -e MYSQL_ROOT_PASSWORD=1111 mysql:5.7
# docker exec -it triple-travelers-club bash
#