server:
  port: 8270

spring:
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    userName: root
    password: 1111
    url: jdbc:mysql://localhost:3894/triple


