version: '3'
services:
  mysql:
    restart: always
    image: mysql:5.7
    container_name: triple_db
    ports:
      - 3302:3306
    environment:
      MYSQL_ROOT_PASSWORD: 1111
      MYSQL_DATABASE: triple_db
    command:
      - --character-set-server=utf8mb3
      - --collation-server=utf8_general_ci
      - --init-file /data/application/prepared.sql
    volumes:
      - ../docker:/var/lib/mysql
      - ./prepared.sql:/data/application/prepared.sqld

# docker run -it -d -p 3302:3306 --name triple-travelers-club -e MYSQL_ROOT_PASSWORD=1111 --restart=always --platform=linux/amd64 mysql:5.7